import 'package:flutter/painting.dart';

const ayuDarkTheme = <String, TextStyle>{
  'root': TextStyle(backgroundColor: Color(0xFF0E0E0E), color: Color(0xFFBFBDB6)),
  'keyword': TextStyle(color: Color(0xFFFF8F40)),
  'literal': TextStyle(color: Color(0xFFD2A6FF)),
  'symbol': TextStyle(color: Color(0xFFD2A6FF)),
  'name': TextStyle(color: Color(0xFF59C2FF)),
  'link': TextStyle(color: Color(0xFF39BAE6)),
  'built_in': TextStyle(color: Color(0xFFFFB454)),
  'type': TextStyle(color: Color(0xFF59C2FF)),
  'number': TextStyle(color: Color(0xFFD2A6FF)),
  'class': TextStyle(color: Color(0xFF59C2FF)),
  'string': TextStyle(color: Color(0xFFAAD94C)),
  'meta-string': TextStyle(color: Color(0xFFAAD94C)),
  'regexp': TextStyle(color: Color(0xFF95E6CB)),
  'template-tag': TextStyle(color: Color(0xFF95E6CB)),
  'template-variable': TextStyle(color: Color(0xFFE6B450)),
  'subst': TextStyle(color: Color(0xFFBFBDB6)),
  'function': TextStyle(color: Color(0xFFFFB454)),
  'title': TextStyle(color: Color(0xFFFFB454)),
  'params': TextStyle(color: Color(0xFFBFBDB6)),
  'formula': TextStyle(color: Color(0xFFBFBDB6)),
  'comment': TextStyle(color: Color(0xFF5C6773), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xFF5C6773), fontStyle: FontStyle.italic),
  'doctag': TextStyle(color: Color(0xFF95E6CB)),
  'meta': TextStyle(color: Color(0xFFE6B450)),
  'meta-keyword': TextStyle(color: Color(0xFFE6B450)),
  'tag': TextStyle(color: Color(0xFF39BAE6)),
  'variable': TextStyle(color: Color(0xFFF07178)),
  'attr': TextStyle(color: Color(0xFFFFB454)),
  'attribute': TextStyle(color: Color(0xFFFFB454)),
  'builtin-name': TextStyle(color: Color(0xFFE6B450)),
  'section': TextStyle(color: Color(0xFF59C2FF), fontWeight: FontWeight.bold),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'bullet': TextStyle(color: Color(0xFFE6B450)),
  'selector-tag': TextStyle(color: Color(0xFF39BAE6)),
  'selector-id': TextStyle(color: Color(0xFFE6B450)),
  'selector-class': TextStyle(color: Color(0xFF59C2FF)),
  'selector-attr': TextStyle(color: Color(0xFFFFB454)),
  'selector-pseudo': TextStyle(color: Color(0xFFFFB454)),
  'addition': TextStyle(backgroundColor: Color(0xFF1A4840)),
  'deletion': TextStyle(backgroundColor: Color(0xFF4A1F1F)),
};

const ayuLightTheme = <String, TextStyle>{
  'root': TextStyle(backgroundColor: Color(0xFFFAFAFA), color: Color(0xFF5C6166)),
  'keyword': TextStyle(color: Color(0xFFFA8D3E)),
  'literal': TextStyle(color: Color(0xFFA37ACC)),
  'symbol': TextStyle(color: Color(0xFFA37ACC)),
  'name': TextStyle(color: Color(0xFF399EE6)),
  'link': TextStyle(color: Color(0xFF55B4D4)),
  'built_in': TextStyle(color: Color(0xFFF2AE49)),
  'type': TextStyle(color: Color(0xFF399EE6)),
  'number': TextStyle(color: Color(0xFFA37ACC)),
  'class': TextStyle(color: Color(0xFF399EE6)),
  'string': TextStyle(color: Color(0xFF86B300)),
  'meta-string': TextStyle(color: Color(0xFF86B300)),
  'regexp': TextStyle(color: Color(0xFF4CBF99)),
  'template-tag': TextStyle(color: Color(0xFF4CBF99)),
  'template-variable': TextStyle(color: Color(0xFFE6BA7E)),
  'subst': TextStyle(color: Color(0xFF5C6166)),
  'function': TextStyle(color: Color(0xFFF2AE49)),
  'title': TextStyle(color: Color(0xFFF2AE49)),
  'params': TextStyle(color: Color(0xFF5C6166)),
  'formula': TextStyle(color: Color(0xFF5C6166)),
  'comment': TextStyle(color: Color(0xFFABB0B6), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xFFABB0B6), fontStyle: FontStyle.italic),
  'doctag': TextStyle(color: Color(0xFF4CBF99)),
  'meta': TextStyle(color: Color(0xFFE6BA7E)),
  'meta-keyword': TextStyle(color: Color(0xFFE6BA7E)),
  'tag': TextStyle(color: Color(0xFF55B4D4)),
  'variable': TextStyle(color: Color(0xFFF07171)),
  'attr': TextStyle(color: Color(0xFFF2AE49)),
  'attribute': TextStyle(color: Color(0xFFF2AE49)),
  'builtin-name': TextStyle(color: Color(0xFFE6BA7E)),
  'section': TextStyle(color: Color(0xFF399EE6), fontWeight: FontWeight.bold),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'bullet': TextStyle(color: Color(0xFFE6BA7E)),
  'selector-tag': TextStyle(color: Color(0xFF55B4D4)),
  'selector-id': TextStyle(color: Color(0xFFE6BA7E)),
  'selector-class': TextStyle(color: Color(0xFF399EE6)),
  'selector-attr': TextStyle(color: Color(0xFFF2AE49)),
  'selector-pseudo': TextStyle(color: Color(0xFFF2AE49)),
  'addition': TextStyle(backgroundColor: Color(0xFFE8F2D8)),
  'deletion': TextStyle(backgroundColor: Color(0xFFFCE4E4)),
};
